// Generated by https://docs.google.com/spreadsheets/d/1AlzHPLXnisMNnQ3OENVSZAYfQ4ZKVRGzkC8vVAt61TM/edit

// X(can_id, name, refresh_interval, ttl, has_safe_state, safe_state)
#define LV3_CAN_Parameters_XMacro \
\
X(0x2000004, sw_hv_main, 0, 500, 1, 0) \
X(0x2000104, sw_hv_motor, 0, 500, 1, 0) \
X(0x2000204, sw_hv_mppt, 0, 500, 1, 0) \
X(0x2000304, sw_motor_reverse, 0, 500, 0, 0) \
X(0x2000404, sw_motor_eco, 0, 500, 0, 0) \
X(0x4000504, sw_service_brake, 0, 500, 0, 0) \
X(0x4000604, sw_parking_brake, 0, 500, 0, 0) \
X(0x4000704, sw_turn_right, 0, 500, 0, 0) \
X(0x4000804, sw_turn_left, 0, 500, 0, 0) \
\
\
X(0x8000008, motor_rpm, 100, 500, 0, 0) \
X(0x4000108, motor_speed, 100, 500, 0, 0) \
X(0xA006408, mppt1_voltage, 500, 2000, 0, 0) \
X(0xA006508, mppt1_current, 500, 2000, 0, 0) \
X(0xA006608, mppt1_batt_rail, 500, 2000, 0, 0) \
X(0xA006708, mppt1_temp, 500, 2000, 0, 0) \
X(0xA00C808, mppt2_voltage, 500, 2000, 0, 0) \
X(0xA00C908, mppt2_current, 500, 2000, 0, 0) \
X(0xA00CA08, mppt2_batt_rail, 500, 2000, 0, 0) \
X(0xA00CB08, mppt2_temp, 500, 2000, 0, 0) \
X(0xA012C08, mppt3_voltage, 500, 2000, 0, 0) \
X(0xA012D08, mppt3_current, 500, 2000, 0, 0) \
X(0xA012E08, mppt3_batt_rail, 500, 2000, 0, 0) \
X(0xA012F08, mppt3_temp, 500, 2000, 0, 0) \
X(0xA019008, mppt4_voltage, 500, 2000, 0, 0) \
X(0xA019108, mppt4_current, 500, 2000, 0, 0) \
X(0xA019208, mppt4_batt_rail, 500, 2000, 0, 0) \
X(0xA019308, mppt4_temp, 500, 2000, 0, 0) \
\
\
X(0x6000110, lv_bat_voltage, 500, 1000, 0, 0) \
X(0x6000210, lv_bat_current, 200, 1000, 0, 0) \
X(0x6000310, lv_sys_current, 200, 1000, 0, 0) \
X(0x6000410, lv_bat_temp, 500, 1000, 0, 0) \
\
\
X(0x400010C, hv_fault, 0, 500, 1, 1) \
X(0x800020C, hv_main_active, 0, 500, 0, 0) \
X(0x800030C, hv_motor_active, 0, 500, 0, 0) \
X(0x800040C, hv_mppt_active, 0, 500, 0, 0) \
X(0x600050C, hv_pack_voltage, 100, 1000, 0, 0) \
X(0x600060C, hv_pack_current, 100, 1000, 0, 0) \
X(0x600070C, hv_pack_temp, 500, 1000, 0, 0) \
X(0x600080C, hv_pack_max_temp, 500, 1000, 0, 0) \
X(0x600090C, hv_pack_soc, 500, 1000, 0, 0) \
X(0xC00640C, hv_cell_voltage_1, 1000, 2000, 0, 0) \
X(0xC00650C, hv_cell_voltage_2, 1000, 2000, 0, 0) \
X(0xC00660C, hv_cell_voltage_3, 1000, 2000, 0, 0) \
X(0xC00670C, hv_cell_voltage_4, 1000, 2000, 0, 0) \
X(0xC00680C, hv_cell_voltage_5, 1000, 2000, 0, 0) \
X(0xC00690C, hv_cell_voltage_6, 1000, 2000, 0, 0) \
X(0xC006A0C, hv_cell_voltage_7, 1000, 2000, 0, 0) \
X(0xC006B0C, hv_cell_voltage_8, 1000, 2000, 0, 0) \
X(0xC006C0C, hv_cell_voltage_9, 1000, 2000, 0, 0) \
X(0xC006D0C, hv_cell_voltage_10, 1000, 2000, 0, 0) \
X(0xC006E0C, hv_cell_voltage_11, 1000, 2000, 0, 0) \
X(0xC006F0C, hv_cell_voltage_12, 1000, 2000, 0, 0) \
X(0xC00700C, hv_cell_voltage_13, 1000, 2000, 0, 0) \
X(0xC00710C, hv_cell_voltage_14, 1000, 2000, 0, 0) \
X(0xC00720C, hv_cell_voltage_15, 1000, 2000, 0, 0) \
X(0xC00730C, hv_cell_voltage_16, 1000, 2000, 0, 0) \
X(0xC00740C, hv_cell_voltage_17, 1000, 2000, 0, 0) \
X(0xC00750C, hv_cell_voltage_18, 1000, 2000, 0, 0) \
X(0xC00760C, hv_cell_voltage_19, 1000, 2000, 0, 0) \
X(0xC00770C, hv_cell_voltage_20, 1000, 2000, 0, 0) \
X(0xC00780C, hv_cell_voltage_21, 1000, 2000, 0, 0) \
X(0xC00790C, hv_cell_voltage_22, 1000, 2000, 0, 0) \
X(0xC007A0C, hv_cell_voltage_23, 1000, 2000, 0, 0) \
X(0xC007B0C, hv_cell_voltage_24, 1000, 2000, 0, 0) \
